ci: run generated eBPF test targets

diff --git a/.github/workflows/bpf-test.yml b/.github/workflows/bpf-test.yml
--- a/.github/workflows/bpf-test.yml
+++ b/.github/workflows/bpf-test.yml
@@ -7,6 +7,9 @@ on:
       - "**/*.h"
       - "go.mod"
       - "go.sum"
+      - ".gitmodules"
+      - "Makefile"
+      - "control/kern/tests/*.go"
       - ".github/workflows/bpf-test.yml"
   push:
     branches:
@@ -16,6 +19,9 @@ on:
       - "**/*.h"
       - "go.mod"
       - "go.sum"
+      - ".gitmodules"
+      - "Makefile"
+      - "control/kern/tests/*.go"
       - ".github/workflows/bpf-test.yml"
 
 permissions: read-all
@@ -57,6 +63,4 @@ jobs:
 
       - name: Run BPF tests
         env: ${{ matrix.env }}
-        run: |
-          git submodule update --init
-          sudo env "PATH=$PATH" CLANG=clang-$VERSION make ebpf-test || (echo "Run 'make ebpf-test' locally to investigate failures"; exit 1)
+        run: sudo env "PATH=$PATH" CLANG=clang-$VERSION make ebpf-test || (echo "Run 'make ebpf-test' locally to investigate failures"; exit 1)
